### ISSUE TITLE
Physics?

### ISSUE THREAD

**Issue by tojaroslaw** [SnorriDev/thoth#16]
We need physics in this game like so stuff can fall and shit

EDIT(lambdaviking): This entails adding velocity (momentum) to entities and gravity.

**Comment by viking-sudo-rm** [comment]
Steps to achieve this:

1. Implement second-order mechanics in `Entity`.
2. Gravity should be applied to entities, and should be disablable using the `isFlying()` API.
3. Don't fall through the floor. Set perpendicular component to 0 on collision.

**Comment by viking-sudo-rm** [comment]
Make sure the implementation allows the direction of gravity to be reversed and stuff. This shouldn't be too hard, but something to keep in mind given some of the use cases we have in mind.
