### ISSUE TITLE
Reformulate flying and jumping for new physics.

### ISSUE THREAD

**Issue by viking-sudo-rm** [SnorriDev/thoth#31]
Old flying meant phasing through blocks. This is no longer an option.

**Comment by viking-sudo-rm** [comment]
Related to #16. Flying now refers to disabling the effects of gravity.

**Comment by legotack** [comment]
Some resources that might be helpful:
http://gameprogrammingpatterns.com/state.html
https://www.youtube.com/watch?v=7KiK0Aqtmzc
https://www.youtube.com/watch?v=hG9SzQxaCm8
(These last two videos say pretty similar things)
